### ISSUE TITLE
The template instantiating problem

### ISSUE THREAD

**Issue by Victorious3** [Princess-org/Princess#30]
I'll cut right to the chase and give an example:

File I:
```
export type S = struct { ... }

export type I = interface {
    def method
}

export def polymorph(i: I) {
    i.method()
}
```

File A:
```
import I
def method(s: S) { ... }
polymorph(s)
```

File B:
```
import I
def method(s: S) { ... }
polymorph(s)
```

In this case both File A and File B define an implementation for I for the type S.
The problem right now is that there's only one instance of polymorph for every given type.
It gets even worse, right now the context isn't considered at all so this would fail anyway.

I need to figure out a way to do this in a performant way without having to generate code for every single implementation.

**Comment by copygirl** [comment]
My suggestion is to make implementations explicit, rather than to just look for functions in the scope that happen to match the interface that is being looked for willy nilly. Something like the following?
```
import I
A_Impl = impl I for S {
  def method(s: S) { ... }
}
polymorph((A_Impl)s)
```
Obviously using some pseudo code here, details to be figured out. Maybe `A_Impl` can be inferred, maybe it doesn't even need to be bound to an identifier. The important thing: The implementation of an interface is owned by the module it's created in and thus has a unique identifier, and can't be confused with another module's implementation.

**Comment by copygirl** [comment]
Personally I feel like more explicit generics would help out here, as well:
```
export def polymorph<T1: Interface1, T2: Interface 2>(i: T1 & T2) {
    // can't use i.method() if both T1 and T2 implement it, so just as an example:
    T1.method(i)
    T2.method(i)
}
// can be called with:
polymorph<I1, I2>(s)
```
Just thinking of what would happen if you want something implementing two or more interfaces. But perhaps something like `polymorph((I1 & I2)s)` would also work. `I1 & I2` would sort of be a supertype of two interfaces.

**Comment by Victorious3** [comment]
I do want to solve this by creating a type for the implemented interface together with its implemented methods so that these can be queried for equality. That way I know if the context change needs a different implementation because I can compare the actual methods on that interface. These types would only exist in the context of calling a polymorphic function and they get created for every interface that gets passed in (and every module). It's basically the automatic way of what you are proposing...

This kind of inference is one of the core aspects of my language and not really up for debate... interfaces don't create distinct types either, like if you have the same interface twice under different names and they have the same methods they are considered equal. And you can pass anything that "implements" one of these interfaces to the other.

About the generics, you are correct that if you pass in I twice it may be different ones. This is also the reason why its not possible to create variables of an interface type, Maybe "interface" isn't the right word for this, They are really concepts that happen to be bound to a type.

```
def polymorph(a: I, b: I) {
    let x: I = a // Not valid
    let y: (type_of a) = a // Valid
    let z = a // Also valid
}
```
That's how things are right now. I do want to introduce a syntax to be able to assert that you need the same I twice, it would look like this:
```
def polymorph(a: type T > I, b: T) {
    let x: T = a // This is valid now
}
```
I do want to be able to create types with the form of `A & B` at some point, but that's not implemented either. Because of the way my types work you can simply implement that by joining the two interfaces together into a third one.

I do not have super or subtypes, there's no type hierarchy at all. 

The inference works in different ways too such as here (this I tested at some point not sure if it works currently)

```
type Vec(type T) = struct { ... }
type List(type T) = interface { // polymorphic type
    def add(t: T) ->T
}

def add(t: Vec(type T), t: T) -> T { ... }

var l: List(int) = ...
var v: Vec(int) = ...
// This works, it knows that Vec(int) implements List(int)
l = v
```
Is this a good idea? I don't know. One issue is that the error messages are unhelpful because a function will just not accept a specific type if it doesn't match the interface, and you don't really know why. But I can definitely enhance the error messages later on.

It's an experiment, really... If it turns out to be a horrible idea in practice I might change things. I would love to have more people use the language and come up with ways to break it.
